### ISSUE TITLE
How to improve the performance of cell2mol, currently it gives analysis for 3 cif files out of 10?

### ISSUE THREAD

**Issue by sagarchem** [lcmd-epfl/cell2mol#3]
Dear Admin,

Q1. I was trying to assign formal oxidation states of Mo in MoxSy clusters using cell2mol. Only 3 out of 10 cif files were successful. Is there a way to improve the performance? These were the common warning (error) it gives:

Error 1: "Missing H atoms from coordinated water in reference molecules"; "Missing H atoms from C in reference molecules"
Error 2: "More than one valid possible charge distribution found"

The following cif files I was using:

ACAXOT, ACAXUZ, ACODAX, ACUTAU, ACUTEY, ACAYAG, ACASUZ, ABTCMO, ACABIQ, ACABOW 

(ACODAX, ABTCMO, ACABIQ were successful)

Q2. Is there any way to utilize cell2mol for user defined cif files (other than CCDC cif files) to assign the formal oxidation state?

**Comment by sagarchem** [comment]
Thank you very much for your reply.

For Q1: All the structures except "ACUTEY" seem to be good crystal structures. Most of the cases there are counter ion(s) and I guess which is fine for cell2mol. Could there be any other reason for the error(s)?

Q3. If there are multiple metal centers (same metal), how to distinguish metal centers? Currently, it's only printing Atomic symbol of the metal and it's corresponding oxidation state, but not distinguishes which metal centers. Can I consider first printed value to be for the first Metal center in the cif file and so on?

**Comment by rlaplaza** [comment]
For Q3: If there are multiple metal centers with different OS there is no way for cell2mol to assess which OS belongs to which metal, because as I said cell2mol only considers charge neutrality and does not map the local environment. That said, in the cell2mol paper we also trained machine learning models to predict OS from local environment. Perhaps you would want to try something like that.

Regarding Q1, from checking some of the structures it seems like there are some oxo(?) groups attached to some metals. This is a problem for cell2mol because oxo groups could potentially be coordinated water molecules with missing hydrogens. Again, there are some automatic checks that attempt to fix this issue (based on the metal type and so on) but they are not always successful. I suspect this is the issue. 

This may be improved in a future release but not at the moment, sadly.

**Comment by sagarchem** [comment]
Thank you very much for the clarification
