### ISSUE TITLE
Difficulty Running xyz2mol.py

### ISSUE THREAD

**Issue by yzimmermann** [lcmd-epfl/cell2mol#5]
I'm currently attempting to utilize  `xyz2mol.py` as a standalone script for converting XYZ files to RDKit Mol objects. Upon reviewing the script, I noticed that the `xyz2AC` function, which seems crucial for generating the adjacency matrix necessary for the conversion, is commented out.

Could you provide any insight or guidance on how the conversion is intended to work in the absence of the `xyz2AC` function? Is there an alternative method or function recommended for generating the AC matrix, or perhaps an updated version of the script that addresses this  gap?

Thank you in advance for your help.

**Comment by rlaplaza** [comment]
You can build an adjacency matrix using covalent radii easily with ASE `get_connectivity_matrix` (see https://wiki.fysik.dtu.dk/ase/ase/neighborlist.html), for instance. 

We don't use that part of the original xyz2mol implementation, since we iteratively adjust connectivities (covalent radii are not perfect!)

Sorry for the delay!

**Comment by rlaplaza** [comment]
On that line, I made a dedicated wrapper for convenience: https://github.com/rlaplaza/smilify

You may find it useful! Im closing the issue.
